
apiVersion: v1
kind: Service
metadata:
    labels:
        app: dialogpt-bento
    name: dialogpt-bento
spec:
    ports:
    - name: predict
      port: 3000
      targetPort: 3000
    selector:
      app: dialogpt-bento
    type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: dialogpt-bento
    name: dialogpt-bento
spec:
    selector:
        matchLabels:
            app: dialogpt-bento
    template:
        metadata:
            labels:
                app: dialogpt-bento
        spec:
            containers:
            - image: localhost:5001/dialogpt-bento
              imagePullPolicy: IfNotPresent
              name: dialogpt-bento
              ports:
              - containerPort: 3000