apiVersion: v1
kind: Service
metadata:
  name: wav2vec-torchserve-svc
spec:
  selector:
    app: wav2vec-torchserve
  ports:
  - protocol: "TCP"
    name: http
    port: 8080
    targetPort: 8080
  - protocol: "TCP"
    name: metrics
    port: 8082
    targetPort: 8082

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wav2vec-torchserve
spec:
  selector:
    matchLabels:
      app: wav2vec-torchserve
  replicas: 1
  template:
    metadata:
      labels:
        app: wav2vec-torchserve
    spec:
      containers:
      - name: wav2vec-torchserve
        image: europe-central2-docker.pkg.dev/careful-rock-397919/mgr-image-registry/wav2vec-torchserve
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8082