apiVersion: v1
kind: Service
metadata:
  name: wav2vec-torchserve-svc
spec:
  selector:
    app: wav2vec-torchserve
  ports:
  - protocol: "TCP"
    name: http
    port: 8080
    targetPort: 8080
  - protocol: "TCP"
    name: metrics
    port: 8081
    targetPort: 8081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wav2vec-torchserve
spec:
  selector:
    matchLabels:
      app: wav2vec-torchserve
  replicas: 1
  template:
    metadata:
      labels:
        app: wav2vec-torchserve
    spec:
      containers:
      - name: wav2vec-torchserve
        image: localhost:5001/wav2vec-test
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8081