apiVersion: v1
kind: Service
metadata:
  name: dialogpt-torchserve-svc
spec:
  selector:
    app: dialogpt-torchserve
  ports:
  - protocol: "TCP"
    name: http
    port: 8080
    targetPort: 8080
  - protocol: "TCP"
    name: metrics
    port: 8082
    targetPort: 8082

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dialogpt-torchserve
spec:
  selector:
    matchLabels:
      app: dialogpt-torchserve
  replicas: 1
  template:
    metadata:
      labels:
        app: dialogpt-torchserve
    spec:
      containers:
      - name: dialogpt-torchserve
        image: localhost:5001/dialogpt-test
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8082